### ISSUE TITLE
Grid Combine Game's to-do list

### ISSUE THREAD

**Issue by tinchodias** [pharo-graphics/Tutorials#10]
- [ ] Fix domain bug (failing test)
- [ ] Another pass OOP on domain
- [ ] Simplify game element
- [ ] Color tiles
- [ ] Add UI tests
- Skins
  - [ ] Create a version without skin (and bloc-pac queries)
  - [ ] Add another skin to have more than one usage example
- [ ] Use a non-default font for tiles (to enrich the game as example)
- [ ] Add a separated score dashboard (instead of using the window title to show score)
- [ ] Add an announcement-free UI, as an alternative architecture to think on
- [ ] Scroll event bursts: find a better solution than isSlideEnabled for a prefixed duration
- [ ] Create home menu where a catalog of game modes are listed, and remember best scores of each mode
- [ ] Deploy standalone

**Comment by tinchodias** [comment]
[ ] Separate games to other repo, e.g. pharo-graphics/games
